CC      = gcc
CCFLAGS = -Wall -Wno-multichar

all: 
	$(CC) $(CCFLAGS) gencorestub.c -o gencorestub 
	$(CC) $(CCFLAGS) genlibstub.c  -o genlibstub

clean:
	rm -f gencorestub.exe genlibstub.exe 
