/*************************************************************************
 *
 * Copyright 2001+ MobileWizardry
 * All rights reserved.
 *
 *************************************************************************/

/*
 * @(#)DAL-missing.inc
 */

/*************************************************************************
 * Configuration
 *************************************************************************/

// none

/*************************************************************************
 * Component Variables
 *************************************************************************/

// none

/*************************************************************************
 * Platform Independent Implementation
 *************************************************************************/

// none

/*************************************************************************
 * Implementation
 *************************************************************************/

// NOTE:
// - the following functions are used through the base SHARK code and
//   must be mapped to the appropriate device level for compiling
//
// #define malloc  malloc
// #define free    free
// #define memset  memset
// #define sprintf sprintf
// #define strlen  strlen
// #define strcat  strcat
// #define strcpy  strcpy
// #define strrev  strrev  

/********************************* EOF ***********************************/
