# ***********************************************************************
#
# Copyright (c) 2002+ MobileWizardry
# All rights reservered.
#
# ***********************************************************************/

# @(#)Makefile
#
# -- Aaron Ardiri (mailto:aaron_ardiri@mobilewizardry.com)
#

# compile requirements
default:
	\!msmob_build.bat
