# ***********************************************************************
# 
# Copyright (c) 2001+ MobileWizardry
# All rights reserved.
#
# ***********************************************************************/

#
# @(#)Makefile
# 

clean:
	rm -rf build
	rm -f ../SHARK-cfg.h

distclean:
	make clean
	rm -f libSHARK*.a
